//go:build integration && livecarrier

package main

// This file drives the production SoftphoneSession, AudioWorklet and worker in
// real headless Chrome processes. Chrome's fake microphone reads deterministic
// speech WAVs generated by eSpeak; no human, physical microphone or speaker is
// involved.

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"net"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/gobwas/ws"
	"github.com/gobwas/ws/wsutil"
)

type liveSpeechFixture struct {
	Path       string  `json:"-"`
	Phrase     string  `json:"phrase"`
	Samples    []int16 `json:"-"`
	SampleRate int     `json:"sample_rate"`
}

type liveBrowserAudioSnapshot struct {
	State       string         `json:"state"`
	Detail      string         `json:"detail"`
	Ready       bool           `json:"ready"`
	MaxMic      float64        `json:"max_mic"`
	MaxSpeaker  float64        `json:"max_speaker"`
	Error       string         `json:"error"`
	Diagnostics map[string]any `json:"diagnostics"`
}

type liveBrowserDirectionEvidence struct {
	Source      liveBrowserAudioSnapshot `json:"source"`
	Destination liveBrowserAudioSnapshot `json:"destination"`
}

type liveBrowserSpeechResult struct {
	Evidence map[string]liveBrowserDirectionEvidence `json:"evidence"`
	Fixtures map[string]liveSpeechFixture            `json:"-"`
}

type liveSpeechRecordingMetrics struct {
	EnvelopeCorrelation float64 `json:"envelope_correlation"`
	ReferenceDurationMS int64   `json:"reference_duration_ms"`
	RecordedRMS         float64 `json:"recorded_rms"`
}

type liveBrowserAssets struct {
	server *httptest.Server
}

const liveSoftphoneAudioHeaderBytes = 16

func TestLiveBrowserSpeechHarnessLocal(t *testing.T) {
	assets := prepareLiveBrowserAssets(t)
	fixture := generateLiveSpeechFixture(t, "local-browser-speech", "en-us+m3", "Apteva local browser speech harness verifies the microphone worklet worker and playback worklet without placing a call.")
	if metrics := analyzeRecordedSpeech(fixture.Samples, fixture.SampleRate, fixture); metrics.EnvelopeCorrelation < 0.99 {
		t.Fatalf("speech-reference detector rejected its fixture: %+v", metrics)
	}
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		conn, _, _, err := ws.UpgradeHTTP(r, w)
		if err != nil {
			return
		}
		defer conn.Close()
		_ = wsutil.WriteServerText(conn, []byte(`{"type":"peer.connected"}`))
		for {
			data, op, err := wsutil.ReadClientData(conn)
			if err != nil {
				return
			}
			if op == ws.OpText {
				var message struct {
					Type  string  `json:"type"`
					Nonce float64 `json:"nonce"`
				}
				if json.Unmarshal(data, &message) == nil && message.Type == "ping" {
					pong, _ := json.Marshal(map[string]any{"type": "pong", "nonce": message.Nonce})
					_ = wsutil.WriteServerText(conn, pong)
				}
				continue
			}
			if op == ws.OpBinary && len(data) > liveSoftphoneAudioHeaderBytes {
				// The production server removes the APT1 timestamp/sequence header
				// before forwarding raw PCM to browser playback.
				_ = wsutil.WriteServerBinary(conn, data[liveSoftphoneAudioHeaderBytes:])
			}
		}
	}))
	defer server.Close()
	mediaURL := "ws" + strings.TrimPrefix(server.URL, "http")
	browser := startLiveSpeechBrowser(t, assets.server.URL, fixture.Path, mediaURL)
	browser.waitState(t, "live", 10*time.Second)
	browser.resetLevels(t)
	browser.setMuted(t, false)
	time.Sleep(3 * time.Second)
	browser.setMuted(t, true)
	snapshot := browser.snapshot(t)
	if snapshot.Error != "" || snapshot.MaxMic < 0.005 || snapshot.MaxSpeaker < 0.003 {
		t.Fatalf("real browser speech harness failed: %+v", snapshot)
	}
	t.Logf("real browser harness passed: mic=%.4f speaker=%.4f", snapshot.MaxMic, snapshot.MaxSpeaker)
}

func prepareLiveBrowserAssets(t *testing.T) liveBrowserAssets {
	t.Helper()
	bun, err := exec.LookPath("bun")
	if err != nil {
		t.Fatal("live browser speech test requires Bun to bundle the production audio module")
	}
	bundlePath := filepath.Join(t.TempDir(), "softphone-audio.js")
	cmd := exec.CommandContext(t.Context(), bun, "build", "ui/softphone-audio.ts", "--target=browser", "--format=esm", "--outfile="+bundlePath)
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("bundle production softphone audio module: %v\n%s", err, output)
	}
	bundle, err := os.ReadFile(bundlePath)
	if err != nil {
		t.Fatal(err)
	}
	worklet, err := os.ReadFile("ui/softphone-worklet.js")
	if err != nil {
		t.Fatal(err)
	}
	worker, err := os.ReadFile("ui/softphone-worker.js")
	if err != nil {
		t.Fatal(err)
	}
	harness := []byte(`<!doctype html><meta charset="utf-8"><title>Apteva live speech test</title>
<script type="module">
import { SoftphoneSession, DEFAULT_SOFTPHONE_AUDIO_OPTIONS } from "/softphone-audio.js";
const query = new URLSearchParams(location.search);
const state = { state: "starting", detail: "", ready: false, maxMic: 0, maxSpeaker: 0, error: "", diagnostics: {} };
let session;
window.__aptevaSpeechTest = {
  snapshot: () => ({ state: state.state, detail: state.detail, ready: state.ready, max_mic: state.maxMic, max_speaker: state.maxSpeaker, error: state.error, diagnostics: state.diagnostics }),
  setMuted: (value) => { session?.setMuted(Boolean(value)); return true; },
  resetLevels: () => { state.maxMic = 0; state.maxSpeaker = 0; return true; },
  stop: () => { session?.stop(); return true; },
};
try {
  session = new SoftphoneSession({
    onState: (value, detail) => { state.state = value; state.detail = detail || ""; },
    onLevels: (mic, speaker) => { state.maxMic = Math.max(state.maxMic, mic || 0); state.maxSpeaker = Math.max(state.maxSpeaker, speaker || 0); },
    onDiagnostics: (value) => {
      state.diagnostics = value || {};
      const micDb = Number(value?.micActiveRmsDbfs);
      if (Number.isFinite(micDb)) state.maxMic = Math.max(state.maxMic, Math.pow(10, micDb / 20));
      state.maxSpeaker = Math.max(state.maxSpeaker, Number(session?.speakerLevel) || 0);
    },
  });
  await session.start(query.get("media"), "/softphone-worklet.js", "/softphone-worker.js", DEFAULT_SOFTPHONE_AUDIO_OPTIONS);
  session.setMuted(true);
  state.ready = true;
} catch (error) {
  state.error = error?.stack || error?.message || String(error);
  state.state = "error";
}
</script>`)
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/", "/index.html":
			w.Header().Set("Content-Type", "text/html; charset=utf-8")
			_, _ = w.Write(harness)
		case "/softphone-audio.js":
			w.Header().Set("Content-Type", "text/javascript; charset=utf-8")
			_, _ = w.Write(bundle)
		case "/softphone-worklet.js":
			w.Header().Set("Content-Type", "text/javascript; charset=utf-8")
			_, _ = w.Write(worklet)
		case "/softphone-worker.js":
			w.Header().Set("Content-Type", "text/javascript; charset=utf-8")
			_, _ = w.Write(worker)
		default:
			http.NotFound(w, r)
		}
	}))
	t.Cleanup(server.Close)
	return liveBrowserAssets{server: server}
}

func generateLiveSpeechFixture(t *testing.T, name, voice, phrase string) liveSpeechFixture {
	t.Helper()
	espeak, err := exec.LookPath("espeak")
	if err != nil {
		t.Fatal("live browser speech test requires eSpeak to generate deterministic microphone speech")
	}
	path := filepath.Join(t.TempDir(), name+".wav")
	cmd := exec.CommandContext(t.Context(), espeak, "-v", voice, "-s", "145", "-a", "150", "-w", path, phrase)
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generate %s speech fixture: %v\n%s", name, err, output)
	}
	file, err := os.Open(path)
	if err != nil {
		t.Fatal(err)
	}
	defer file.Close()
	info, err := inspectPCM16WAV(file)
	if err != nil {
		t.Fatalf("inspect generated %s speech: %v", name, err)
	}
	samples := make([]int16, 0, info.DataSize/int64(info.Channels*2))
	if err := forEachWAVFrame(file, info, func(frame []int16) error {
		var sum int64
		for _, sample := range frame {
			sum += int64(sample)
		}
		samples = append(samples, int16(sum/int64(len(frame))))
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	if len(samples) < info.SampleRate {
		t.Fatalf("generated %s speech fixture is too short", name)
	}
	return liveSpeechFixture{Path: path, Phrase: phrase, Samples: samples, SampleRate: info.SampleRate}
}

func runLiveBrowserSpeech(t *testing.T, cfg liveCarrierConfig, outbound, inbound softphoneSession) liveBrowserSpeechResult {
	t.Helper()
	assets := prepareLiveBrowserAssets(t)
	fixtures := map[string]liveSpeechFixture{
		"outbound_to_inbound": generateLiveSpeechFixture(t, "outbound-speech", "en-us+m3", "Apteva browser voice quality test. Clear speech should cross the carrier without static clipping or missing words. Alpha seven maple river."),
		"inbound_to_outbound": generateLiveSpeechFixture(t, "inbound-speech", "en-us+f3", "The return channel checks intelligibility and timing. Please preserve every syllable without cuts or watery noise. Bravo nine silver garden."),
	}
	outboundBrowser := startLiveSpeechBrowser(t, assets.server.URL, fixtures["outbound_to_inbound"].Path, outbound.MediaURL)
	inboundBrowser := startLiveSpeechBrowser(t, assets.server.URL, fixtures["inbound_to_outbound"].Path, inbound.MediaURL)
	outboundBrowser.waitState(t, "live", 20*time.Second)
	inboundBrowser.waitState(t, "live", 20*time.Second)
	outboundBrowser.setMuted(t, true)
	inboundBrowser.setMuted(t, true)

	evidence := make(map[string]liveBrowserDirectionEvidence, 2)
	for _, direction := range []struct {
		name                string
		source, destination *liveSpeechBrowser
	}{
		{"outbound_to_inbound", outboundBrowser, inboundBrowser},
		{"inbound_to_outbound", inboundBrowser, outboundBrowser},
	} {
		direction.source.resetLevels(t)
		direction.destination.resetLevels(t)
		direction.source.setMuted(t, false)
		time.Sleep(6 * time.Second)
		direction.source.setMuted(t, true)
		time.Sleep(500 * time.Millisecond)
		source := direction.source.snapshot(t)
		destination := direction.destination.snapshot(t)
		if source.Error != "" || destination.Error != "" || source.State != "live" || destination.State != "live" {
			t.Fatalf("%s browser speech session failed: source=%+v destination=%+v", direction.name, source, destination)
		}
		if source.MaxMic < 0.005 || destination.MaxSpeaker < 0.003 {
			t.Fatalf("%s browser speech did not traverse the real worklets: source_mic=%.5f destination_speaker=%.5f", direction.name, source.MaxMic, destination.MaxSpeaker)
		}
		evidence[direction.name] = liveBrowserDirectionEvidence{Source: source, Destination: destination}
	}
	t.Log("real Chrome speech capture and playback passed in both directions")
	return liveBrowserSpeechResult{Evidence: evidence, Fixtures: fixtures}
}

func analyzeRecordedSpeech(recorded []int16, recordedRate int, fixture liveSpeechFixture) liveSpeechRecordingMetrics {
	const frameMS = 20
	referenceEnvelope := speechRMSEnvelope(fixture.Samples, fixture.SampleRate, frameMS)
	recordedEnvelope := speechRMSEnvelope(recorded, recordedRate, frameMS)
	if len(referenceEnvelope) == 0 || len(recordedEnvelope) == 0 {
		return liveSpeechRecordingMetrics{}
	}
	peak := 0.0
	for _, value := range referenceEnvelope {
		peak = math.Max(peak, value)
	}
	start := 0
	for start < len(referenceEnvelope) && referenceEnvelope[start] < peak*0.08 {
		start++
	}
	end := len(referenceEnvelope)
	for end > start && referenceEnvelope[end-1] < peak*0.08 {
		end--
	}
	// Scan two-second cadence signatures across the reference because Chrome's
	// looping fake microphone can be at any phrase offset when it is unmuted.
	length := min(100, end-start)
	if length < 50 || len(recordedEnvelope) < length {
		return liveSpeechRecordingMetrics{}
	}
	bestCorrelation, bestOffset := -1.0, 0
	for referenceOffset := start; referenceOffset+length <= end; referenceOffset += 5 {
		signature := referenceEnvelope[referenceOffset : referenceOffset+length]
		for offset := 0; offset+length <= len(recordedEnvelope); offset++ {
			correlation := normalizedFloatCorrelation(signature, recordedEnvelope[offset:offset+length])
			if correlation > bestCorrelation {
				bestCorrelation, bestOffset = correlation, offset
			}
		}
	}
	var energy float64
	for _, value := range recordedEnvelope[bestOffset : bestOffset+length] {
		energy += value * value
	}
	return liveSpeechRecordingMetrics{
		EnvelopeCorrelation: bestCorrelation,
		ReferenceDurationMS: int64(length * frameMS),
		RecordedRMS:         math.Sqrt(energy / float64(length)),
	}
}

func speechRMSEnvelope(samples []int16, sampleRate, frameMS int) []float64 {
	frame := sampleRate * frameMS / 1000
	if frame <= 0 {
		return nil
	}
	out := make([]float64, 0, len(samples)/frame)
	for offset := 0; offset+frame <= len(samples); offset += frame {
		var energy float64
		for _, sample := range samples[offset : offset+frame] {
			value := float64(sample)
			energy += value * value
		}
		out = append(out, math.Sqrt(energy/float64(frame)))
	}
	return out
}

func normalizedFloatCorrelation(left, right []float64) float64 {
	if len(left) == 0 || len(left) != len(right) {
		return 0
	}
	var leftMean, rightMean float64
	for index := range left {
		leftMean += left[index]
		rightMean += right[index]
	}
	leftMean /= float64(len(left))
	rightMean /= float64(len(right))
	var dot, leftEnergy, rightEnergy float64
	for index := range left {
		leftValue := left[index] - leftMean
		rightValue := right[index] - rightMean
		dot += leftValue * rightValue
		leftEnergy += leftValue * leftValue
		rightEnergy += rightValue * rightValue
	}
	if leftEnergy == 0 || rightEnergy == 0 {
		return 0
	}
	return dot / math.Sqrt(leftEnergy*rightEnergy)
}

func chromeExecutable() (string, error) {
	if configured := strings.TrimSpace(os.Getenv("TELEPHONY_LIVE_CHROME")); configured != "" {
		if info, err := os.Stat(configured); err == nil && !info.IsDir() {
			return configured, nil
		}
		return "", fmt.Errorf("TELEPHONY_LIVE_CHROME does not point to a file: %s", configured)
	}
	for _, name := range []string{"google-chrome", "chromium", "chromium-browser"} {
		if path, err := exec.LookPath(name); err == nil {
			return path, nil
		}
	}
	if runtime.GOOS == "darwin" {
		path := "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
		if _, err := os.Stat(path); err == nil {
			return path, nil
		}
	}
	return "", errors.New("Google Chrome or Chromium not found; set TELEPHONY_LIVE_CHROME")
}

type liveSpeechBrowser struct {
	cmd       *exec.Cmd
	cdp       *liveCDPClient
	sessionID string
}

func startLiveSpeechBrowser(t *testing.T, assetsURL, speechPath, mediaURL string) *liveSpeechBrowser {
	t.Helper()
	chrome, err := chromeExecutable()
	if err != nil {
		t.Fatal(err)
	}
	profile := t.TempDir()
	var stderr bytes.Buffer
	cmd := exec.CommandContext(t.Context(), chrome,
		"--headless=new", "--disable-gpu", "--no-sandbox", "--no-first-run", "--no-default-browser-check",
		"--disable-background-timer-throttling", "--disable-renderer-backgrounding", "--disable-backgrounding-occluded-windows",
		"--autoplay-policy=no-user-gesture-required", "--use-fake-ui-for-media-stream", "--use-fake-device-for-media-stream",
		"--use-file-for-fake-audio-capture="+speechPath, "--remote-allow-origins=*", "--remote-debugging-port=0",
		"--user-data-dir="+profile, "about:blank")
	cmd.Stderr = &stderr
	if err := cmd.Start(); err != nil {
		t.Fatalf("start Chrome: %v", err)
	}
	browser := &liveSpeechBrowser{cmd: cmd}
	t.Cleanup(func() { browser.close() })

	activePort := filepath.Join(profile, "DevToolsActivePort")
	var browserWS string
	deadline := time.Now().Add(10 * time.Second)
	for time.Now().Before(deadline) {
		raw, readErr := os.ReadFile(activePort)
		if readErr == nil {
			parts := strings.Split(strings.TrimSpace(string(raw)), "\n")
			if len(parts) >= 2 {
				browserWS = "ws://127.0.0.1:" + parts[0] + parts[1]
				break
			}
		}
		if cmd.ProcessState != nil && cmd.ProcessState.Exited() {
			t.Fatalf("Chrome exited before DevTools was ready: %s", stderr.String())
		}
		time.Sleep(50 * time.Millisecond)
	}
	if browserWS == "" {
		t.Fatalf("Chrome DevTools did not become ready: %s", stderr.String())
	}
	browser.cdp = newLiveCDPClient(t, browserWS)
	targetURL := assetsURL + "/?media=" + url.QueryEscape(mediaURL)
	var target struct {
		TargetID string `json:"targetId"`
	}
	browser.cdp.call(t, "", "Target.createTarget", map[string]any{"url": targetURL}, &target)
	browser.cdp.call(t, "", "Target.activateTarget", map[string]any{"targetId": target.TargetID}, nil)
	var attached struct {
		SessionID string `json:"sessionId"`
	}
	browser.cdp.call(t, "", "Target.attachToTarget", map[string]any{"targetId": target.TargetID, "flatten": true}, &attached)
	browser.sessionID = attached.SessionID
	browser.cdp.call(t, browser.sessionID, "Runtime.enable", map[string]any{}, nil)
	browser.waitReady(t, 15*time.Second)
	return browser
}

func (b *liveSpeechBrowser) evaluate(t *testing.T, expression string, out any) {
	t.Helper()
	var result struct {
		Result struct {
			Value json.RawMessage `json:"value"`
		} `json:"result"`
		Exception json.RawMessage `json:"exceptionDetails"`
	}
	b.cdp.call(t, b.sessionID, "Runtime.evaluate", map[string]any{
		"expression": expression, "returnByValue": true, "awaitPromise": true,
	}, &result)
	if len(result.Exception) > 0 && string(result.Exception) != "null" {
		t.Fatalf("Chrome evaluation failed: %s", result.Exception)
	}
	if out != nil && len(result.Result.Value) > 0 {
		if err := json.Unmarshal(result.Result.Value, out); err != nil {
			t.Fatalf("decode Chrome evaluation: %v value=%s", err, result.Result.Value)
		}
	}
}

func (b *liveSpeechBrowser) snapshot(t *testing.T) liveBrowserAudioSnapshot {
	t.Helper()
	var value liveBrowserAudioSnapshot
	b.evaluate(t, "window.__aptevaSpeechTest?.snapshot() || ({state:'loading'})", &value)
	return value
}

func (b *liveSpeechBrowser) waitReady(t *testing.T, timeout time.Duration) {
	t.Helper()
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		value := b.snapshot(t)
		if value.Error != "" {
			t.Fatalf("Chrome softphone startup failed: %s", value.Error)
		}
		if value.Ready {
			return
		}
		time.Sleep(100 * time.Millisecond)
	}
	t.Fatalf("Chrome softphone did not become ready: %+v", b.snapshot(t))
}

func (b *liveSpeechBrowser) waitState(t *testing.T, state string, timeout time.Duration) {
	t.Helper()
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		value := b.snapshot(t)
		if value.Error != "" || value.State == "error" {
			t.Fatalf("Chrome softphone failed while waiting for %s: %+v", state, value)
		}
		if value.State == state {
			return
		}
		time.Sleep(100 * time.Millisecond)
	}
	t.Fatalf("Chrome softphone did not reach %s: %+v", state, b.snapshot(t))
}

func (b *liveSpeechBrowser) setMuted(t *testing.T, muted bool) {
	t.Helper()
	b.evaluate(t, "window.__aptevaSpeechTest.setMuted("+strconv.FormatBool(muted)+")", nil)
}

func (b *liveSpeechBrowser) resetLevels(t *testing.T) {
	t.Helper()
	b.evaluate(t, "window.__aptevaSpeechTest.resetLevels()", nil)
}

func (b *liveSpeechBrowser) close() {
	if b.cdp != nil {
		b.cdp.close()
	}
	if b.cmd != nil && b.cmd.Process != nil {
		_ = b.cmd.Process.Kill()
		_, _ = b.cmd.Process.Wait()
	}
}

type liveCDPResponse struct {
	ID     int64           `json:"id"`
	Result json.RawMessage `json:"result"`
	Error  *struct {
		Code    int    `json:"code"`
		Message string `json:"message"`
	} `json:"error"`
}

type liveCDPClient struct {
	conn    net.Conn
	writeMu sync.Mutex
	mu      sync.Mutex
	nextID  atomic.Int64
	pending map[int64]chan liveCDPResponse
	closed  chan struct{}
}

func newLiveCDPClient(t *testing.T, endpoint string) *liveCDPClient {
	t.Helper()
	conn, buffered, _, err := ws.Dial(t.Context(), endpoint)
	if err != nil {
		t.Fatalf("connect Chrome DevTools: %v", err)
	}
	if buffered != nil {
		conn = hijackedConn{Conn: conn, reader: buffered}
	}
	client := &liveCDPClient{conn: conn, pending: map[int64]chan liveCDPResponse{}, closed: make(chan struct{})}
	go client.readLoop()
	return client
}

func (c *liveCDPClient) readLoop() {
	defer close(c.closed)
	for {
		data, op, err := wsutil.ReadServerData(c.conn)
		if err != nil {
			return
		}
		if op != ws.OpText {
			continue
		}
		var response liveCDPResponse
		if json.Unmarshal(data, &response) != nil || response.ID == 0 {
			continue
		}
		c.mu.Lock()
		channel := c.pending[response.ID]
		delete(c.pending, response.ID)
		c.mu.Unlock()
		if channel != nil {
			channel <- response
		}
	}
}

func (c *liveCDPClient) call(t *testing.T, sessionID, method string, params any, out any) {
	t.Helper()
	id := c.nextID.Add(1)
	channel := make(chan liveCDPResponse, 1)
	c.mu.Lock()
	c.pending[id] = channel
	c.mu.Unlock()
	request := map[string]any{"id": id, "method": method, "params": params}
	if sessionID != "" {
		request["sessionId"] = sessionID
	}
	payload, err := json.Marshal(request)
	if err != nil {
		t.Fatal(err)
	}
	c.writeMu.Lock()
	err = wsutil.WriteClientText(c.conn, payload)
	c.writeMu.Unlock()
	if err != nil {
		t.Fatalf("Chrome DevTools %s write: %v", method, err)
	}
	select {
	case response := <-channel:
		if response.Error != nil {
			t.Fatalf("Chrome DevTools %s: code=%d message=%s", method, response.Error.Code, response.Error.Message)
		}
		if out != nil && len(response.Result) > 0 {
			if err := json.Unmarshal(response.Result, out); err != nil {
				t.Fatalf("decode Chrome DevTools %s: %v result=%s", method, err, response.Result)
			}
		}
	case <-c.closed:
		t.Fatalf("Chrome DevTools closed during %s", method)
	case <-time.After(10 * time.Second):
		t.Fatalf("Chrome DevTools %s timed out", method)
	}
}

func (c *liveCDPClient) close() {
	if c.conn != nil {
		_ = c.conn.Close()
	}
}
